- name: 긴급
  color: ff0000
  description: 긴급한 작업

- name: 문서
  color: 000000
  description: 문서 작업 관련

- name: 버그
  color: 5715EE
  description: 버그 수정이 필요한 작업

- name: 보류
  color: D00ACE
  description: 추후 작업 진행 예정

- name: 작업 완료
  color: 0000ff
  description: 작업 완료 상태인 경우 (이슈 폐쇄)

- name: 작업 전
  color: E6D4AE
  description: 작업 시작 전 준비 상태

- name: 작업 중
  color: a2eeef
  description: 작업이 진행 중인 상태

- name: 취소
  color: f28b25
  description: 작업 취소됨

- name: 담당자 확인 중
  color: ffd700
  description: 담당자 확인 중 (담당자 확인 후 '작업완료' or '피드백')

- name: 피드백
  color: 228b22
  description: 담당자 확인 후 수정 필요

- name: feat
  color: 14b8a6
  description: 새로운 기능 추가 (Feature)

- name: enhancement
  color: 22c55e
  description: 기능 개선/향상 (Enhancement)

- name: fix
  color: f43f5e
  description: 버그 수정 (Fix)

- name: hotfix
  color: 0ea5e9
  description: 긴급 핫픽스 (Hotfix)

- name: chore
  color: 64748b
  description: 유지보수/빌드/잡무 (Chore)

- name: refactor
  color: d946ef
  description: 리팩터링 (Refactor)

- name: ci
  color: 0369a1
  description: CI/CD 파이프라인/워크플로 변경 (CI)

- name: skip-release
  color: 94a3b8
  description: 자동 릴리스 노트에서 제외할 때 사용
